# Generated by Django 5.0.6 on 2024-05-25 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("progress_tracking", "0004_wordprediction"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WordPrediction",
        ),
    ]
