"use client";
import "bootstrap/dist/css/bootstrap.css";
import { Inter } from "next/font/google";
import "./globals.css";

import { Toaster } from "sonner";

import Navbar from "@/app/components/navbar/Navbar";

import BootstrapClient from "./components/BootstrapClient";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster richColors closeButton position="top-right" />
        <Navbar />
        {children}

        <BootstrapClient />
      </body>
    </html>
  );
}
