services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=word_mentor
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   restart: always
  #   ports:
  #     - "8888:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: root@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - db
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - 6379

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: /docker/backend/startup.sh
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
    
  celery:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: celery -A backend worker --uid nobody -l info
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - TRANSFORMERS_CACHE=/tmp/transformers_cache
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  
volumes:
  db-data:
  pgadmin-data:

secrets:
  db-password:
    file: db/password.txt
