services:
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    expose:
      - 6379

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command:  python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
 
    
  # celery:
  #   build:
  #     context: ./backend_celery
  #     dockerfile: ./Dockerfile
  #   command: celery -A backend_celery worker --uid nobody -l info
  #   volumes:
  #     - ./backend_celery:/app/backend_celery
  #   env_file:
  #     - ./backend_celery/.env
  #   environment:
  #    - HF_HOME=/tmp/transformers_cache
  #    - TRANSFORMERS_CACHE=/tmp/transformers_cache
  #    - REDIS_HOST=redis
  #    - REDIS_PORT=6379
   

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  
