version: '3.8'

services:

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: ["sh", "/app/entrypoint.sh"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  db-data:
