[tool.ruff]
line-length = 121
indent-width = 4

[tool.ruff.lint]
# Default for `select` is ["E4", "E7", "E9", "F"]
# All additional rules must be added using `extend-select`.
extend-select = [
    "E",
    "W",
    "I",     # isort, https://docs.astral.sh/ruff/rules/#isort-i
    "UP",    # pyupgrade, https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "ASYNC",
    "B002",
    "B015",
    "B033",
    "B025",
    "A",
    "T10",
    "T20",
    "DJ",    # flake8-django https://docs.astral.sh/ruff/rules/#flake8-django-dj,
    "PLE",
]
ignore = [
    "PLR5501", # collapsible-else-if https://docs.astral.sh/ruff/rules/collapsible-else-if/#collapsible-else-if-plr5501
    "UP031",   # printf-string-formatting https://docs.astral.sh/ruff/rules/printf-string-formatting/
    "UP032",   # f-string https://docs.astral.sh/ruff/rules/f-string/
    "A001",    # builtin-variable-shadowing https://docs.astral.sh/ruff/rules/builtin-variable-shadowing/
    "A002",    # builtin-argument-shadowing https://docs.astral.sh/ruff/rules/builtin-argument-shadowing/
    "DJ001",   # django-nullable-model-string-field https://docs.astral.sh/ruff/rules/django-nullable-model-string-field/
    "DJ008",   # django-model-without-dunder-str https://docs.astral.sh/ruff/rules/django-model-without-dunder-str/
    "DJ012",   # django-unordered-body-content-in-model https://docs.astral.sh/ruff/rules/django-unordered-body-content-in-model/
    "DJ007",   # django-all-with-model-form https://docs.astral.sh/ruff/rules/django-all-with-model-form/
]

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "preserve"

[tool.ruff.lint.isort]
lines-after-imports = 2
section-order = [
    "future",
    "standard-library",
    "django",
    "third-party",
    "src",
    "first-party",
    "local-folder",
]
relative-imports-order = "closest-to-furthest"


[tool.ruff.lint.isort.sections]
django = [
    "django",
    "rest_framework",
    "rest_flex_fields",
    "drf_extra_fields",
    "djangorestframework_camel_case",
    "drf_yasg",
]
src = [
    "backend",
    "core",
    "books",
    "progress_tracking",
    "settings",
    "word",
    "wordmentor_auth",
]

[tool.ruff.lint.per-file-ignores]
"*/tests/*" = ["T201", "T203"]
"*/management/*" = ["T201", "T203"]
