# Generated by Django 5.0.6 on 2024-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_profile_has_taken_assessment"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="task",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
