# Generated by Django 5.0.6 on 2024-05-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0006_profile_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="task",
        ),
    ]
