# Generated by Django 5.0.6 on 2024-05-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_remove_profile_restored_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="deleted_at",
        ),
    ]
