# Generated by Django 5.0.6 on 2024-05-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0011_profile_assessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='known_words',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='unknown_words',
        ),
    ]
