# Generated by Django 5.0.6 on 2024-06-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0013_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
