# Generated by Django 5.0.6 on 2024-06-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0004_wordnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordnet',
            name='example_sentence',
            field=models.TextField(default=''),
        ),
    ]
