# Generated by Django 5.0.6 on 2024-06-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word", "0005_alter_wordnet_example_sentence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordnet",
            name="example_sentence",
            field=models.TextField(blank=True, default=""),
        ),
    ]
