# Generated by Django 5.0.6 on 2024-06-08 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("word", "0008_word_created_at_word_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordMeaning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
                ("part_of_speech", models.CharField(max_length=50)),
                ("example_sentence", models.TextField()),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="word.word"
                    ),
                ),
            ],
        ),
    ]
