# Generated by Django 5.0.6 on 2024-05-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordmentor_auth", "0003_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="restored_at",
        ),
    ]
