# Generated by Django 5.0.5 on 2024-05-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0005_profile_has_taken_assessment"),
        ("trainedmodels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainedmodel",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="settings.profile",
            ),
        ),
    ]
