# Generated by Django 5.0.6 on 2024-05-10 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainedmodels", "0003_remove_trainedmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainedmodel",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
