# Generated by Django 5.0.6 on 2024-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainedmodels", "0004_trainedmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainedmodel",
            name="celery_task_id",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
