# Generated by Django 5.0.6 on 2024-05-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainedmodels', '0005_trainedmodel_celery_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainedmodel',
            name='restored_at',
        ),
    ]
