# Generated by Django 5.0.6 on 2024-05-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainedmodels", "0006_remove_trainedmodel_restored_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainedmodel",
            name="deleted_at",
        ),
    ]
