# Generated by Django 5.0.6 on 2024-05-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainedmodels", "0007_remove_trainedmodel_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainedmodel",
            name="celery_task_id",
        ),
    ]
