# Generated by Django 5.0.6 on 2024-05-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_book_restored_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="deleted_at",
        ),
    ]
