name: Deploy Word Mentor Application

on:
  push:
    branches:
      - 'producation'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: Install gcloud CLI
      uses: google-github-actions/setup-gcloud@v2

    - name: Build and push the backend Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        MODE: ${{ secrets.MODE }}
        X_RAPID_API_KEY: ${{ secrets.X_RAPID_API_KEY }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/demo/backend:latest ./backend
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/backend:latest

    - name: Deploy backend to Cloud Run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        MODE: ${{ secrets.MODE }}
        X_RAPID_API_KEY: ${{ secrets.X_RAPID_API_KEY }}
      run: |
        gcloud run deploy backend \
          --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/backend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --update-env-vars MODE=${{ secrets.MODE }},X_RAPID_API_KEY=${{ secrets.X_RAPID_API_KEY }}

    - name: Build and push the frontend Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        

      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/demo/frontend:latest ./frontend
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/demo/frontend:latest

    - name: Deploy frontend to Cloud Run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        NEXT_PUBLIC_API_HOST: ${{ secrets.NEXT_PUBLIC_API_HOST }}
        NEXT_PUBLIC_FRONTEND_HOST: ${{ secrets.NEXT_PUBLIC_FRONTEND_HOST }}
        NEXT_PUBLIC_BACKEND_HOST: ${{ secrets.NEXT_PUBLIC_BACKEND_HOST }}
      run: |
        gcloud run deploy frontend \
          --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/frontend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --update-env-vars NEXT_PUBLIC_API_HOST=${{ secrets.NEXT_PUBLIC_API_HOST }},NEXT_PUBLIC_FRONTEND_HOST=${{ secrets.NEXT_PUBLIC_FRONTEND_HOST }},NEXT_PUBLIC_BACKEND_HOST=${{ secrets.NEXT_PUBLIC_BACKEND_HOST }}
    
    