name: Deploy frontend

on:
  push:
    branches:
    - producation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      id: cache-docker-layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2

    - name: build and push the frontend Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
                            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                            --tag us-central1-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/demo/frontend:latest \
                            --push ./frontend
        mv /tmp/.buildx-cache-new/* /tmp/.buildx-cache/

    - name: Deploy frontend to Cloud Run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud run deploy frontend \
          --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/frontend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
    
    - name: build and push the backend Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
                            --cache-to=type=local,dest=/tmp/.buildx-cache-new \
                            --tag us-central1-docker.pkg.dev/${{secrets.GOOGLE_PROJECT}}/demo/backend:latest \
                            --push ./backend
        mv /tmp/.buildx-cache-new/* /tmp/.buildx-cache/

    - name: Deploy backend to Cloud Run
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud run deploy backend \
          --image us-central1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/demo/backend:latest \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
